### ISSUE TITLE
LoRRA model freezes RAM while loading moudle wiki.en.bin file 

### ISSUE THREAD

**Issue by CS19F005** [facebookresearch/mmf#202]
## ❓ Questions and Help

Hi while trying to reproduce LoRRA model on Text VQA, my computer freezes indefinitely while loading `fasttext model from .vector_cache/wiki.en.bin`. 
I have 16GB of RAM and I followed the instructions on the README homepage of Pythia. 
Running the following command
```
python tools/run.py --tasks vqa --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yml \
--run_type inference --evalai_inference 1 --resume_file data/models/lorra_best.pth
```
any suggestions if i can make it work on my computer, or is 16GB memory insufficient to run LoRRA?

**Comment by apsdehal** [comment]
It should be enough. Please set `--num_workers 0`

**Comment by Thalaivar** [comment]
I am also facing this issue. I am  performing training on Colab with:
!python tools/run.py --tasks vqa --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yml --num_workers 0

**Comment by apsdehal** [comment]
Can you provide the colab link to me?

**Comment by Thalaivar** [comment]
Sure (excuse the mess :p): https://colab.research.google.com/drive/1SkQCzh5MZMkTjQAXfo0HymnOzV_K3BHO

**Comment by apsdehal** [comment]
Thanks. I checked your colab and you are indeed getting memory issues. 

Since this is colab, it has just enough memory to run LoRRA but the downside is that it requires some hacks. You have to garbage collect all the time and then clear the cuda cache. I have this unofficial demo of LoRRA which we never made public due to issues with memory. It is available at [this link](https://colab.research.google.com/drive/120xCDefxsqAmm7l6uf5nFDx5zr7msA0R). See if this helps you. It usually works fine, but sometimes goes OOM.

**Comment by Thalaivar** [comment]
Thanks!
btw, how much memory is required to satisfactorily run LoRRA?

**Comment by apsdehal** [comment]
Fasttext model only requires 8GB or so, but PyTorch model also requires some memory, my estimate is around 14GB or so. See #188 for alternative on model size of fasttext.
