### ISSUE TITLE
Feature Extraction using Detectron2

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/mmf#206]
## 🚀 Feature

Based on #193, we definitely need to move to Detectron2 as soon as possible for feature extraction. This would also allow faster e2e training. 

## Motivation

Detectron2 https://github.com/facebookresearch/detectron2 is going to maintained in future rather than maskrcnn-benchmark and detectron and thus we need to move to it. We need to implement similar features in our fork of detectron like we did for vqa-maskrcnn-benchmark.

## Pitch

- Look into the changes that were made to original maskrcnn-benchmark to create vqa-maskrcnn-benchmark. See the [diff](https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark/compare/0dfac376668a6618ed17c2d890c92728bb2926b6...master).
- Fork [detectron2](https://github.com/facebookresearch/detectron2)
- First read the breaking changes in detectron2 compared to detectron/maskrcnn-benchmark at this [link](https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-detectron).
- Make changes according to the diff above to your fork and try training a model.

**Comment by przemb** [comment]
Hi @apsdehal, 
I don't have much experience with detectron2, but according to this [video](https://www.youtube.com/watch?v=egs0XN-xjA0) suggested way instead of creating a new fork is to use customization mechanisms. (to keep maintenance of apps created in FAIR easier).
Do you think if this is sufficient for Pythia?

I don't feel confident to port it myself, but I could share below links which might be helpful:
https://www.dropbox.com/s/o83efjejx1kfrsy/ICCV19_Detectron2.pdf?dl=0 - tutorial ICCV19 - please check the second part of the presentation 
https://github.com/facebookresearch/detectron2/tree/master/projects - existing projects build on top of detectron2

**Comment by zhiqwang** [comment]
Agree with @przemb
