### ISSUE TITLE
Pythia VQA，  BUTD Captioning  Use Chinese dataset

### ISSUE THREAD

**Issue by cylvzj** [facebookresearch/mmf#218]
## ❓ Questions and Help
Hello, please ask.
For these two demos, I changed the data set to Chinese. Do I still need to adjust the algorithm?
What should I do if adjustments are needed?

Looking forward to your reply

**Comment by vedanuj** [comment]
You will need to extract features for the images in your new dataset, some new model for embeddings to replace fastText since it supports English and also vocabulary files. There might be other things you will need to change. Let us know how it works and if there are other changes you required to make your dataset work.

**Comment by cylvzj** [comment]
@vedanuj hello

We want to make an app based on Pythia to help blind people understand the situation around them. The first thing we thought of was to directly translate the coco dataset and train it into a Chinese model. If so, do you need to replace fastText? Or, what changes need to be made?

**Comment by vedanuj** [comment]
If you are translating the Chinese sentences to English and then training the Pythia model with Enlish sentences, then it should work without any changes. But if you are training with Chinese sentences then you need a model similar to `fasttext` that can give you Chinese word embeddings.

**Comment by cylvzj** [comment]
@vedanuj 

Is it OK to use Chinese word segmentation of Jieba?
