### ISSUE TITLE
Stop/Pause training process

### ISSUE THREAD

**Issue by Ra0k** [facebookresearch/mmf#298]
## ❓ Questions and Help

Is it possible to save the current model and stop the training process before it finishes?

I started it by the following command:
`python mmf_cli/run.py config=projects/pythia/configs/textvqa/defaults.yaml datasets=textvqa model=pythia run_type=train_val`

The reason behind it is that I noticed the eta according to the train.log file is 163h 57m 35s 140ms, I can't wait so long but I would like to use the result that is already computed.

**Comment by apsdehal** [comment]
You should use pretrained model for `M4C` in that case. On the other hand, there are multiple ways to increase speed:

1. Increase the `training.evaluation_interval` to a bigger number so that it doesn't evaluate that often
2. I am not sure how many GPUs you are using but this should not be this slow
3. First iteration usually is slow, it will speed up after that.
4. Use `training.pin_memory=True` to pin the memory and speed up things further.
5. Increase `training.num_workers` if you have RAM available.

The models are saved on every `training.checkpoint_interval` which is set to 1000. The models are saved in `<save_dir>/models/` directory and current model is saved as `<save_dir>/current.ckpt` which you can use directly. You can decrease `training.checkpoint_interval` to checkpoint more often and get the model early.

**Comment by Ra0k** [comment]
Thank you!

**Comment by mikolasan** [comment]
It is not possible to stop `mmf_run` with Ctrl+C. I have to kill processes to abort the calculation once it has reached a checkpoint. So I think, the initial question is not resolved. What do you think?
