### ISSUE TITLE
confused on m4c mmt decoder

### ISSUE THREAD

**Issue by shine-lcy** [facebookresearch/mmf#427]
## ❓ Questions and Help
In M4C paper, the output of mmt decoder is a d-dimensional vector, and we use this d-dimensional vector to calculate two scores and obtain next decoder input, which is also a d-dimensional vector. 
However, the size ofoutput of mmt decoder in the code is 12xd, and calculate the scores for each d-dimensional vector of 12. Then replace the answer embedding in 12 positions as a whole for next decode step.
```
for _ in range(dec_step_num):
      self._forward_mmt(sample_list, fwd_results)
      self._forward_output(sample_list, fwd_results)
      argmax_inds = fwd_results["scores"].argmax(dim=-1)
      fwd_results["prev_inds"][:, 1:] = argmax_inds[:, :-1]
```
My understanding of this code is that each decoding step predicts all 12 answers, and then uses the whole as the input of the next decode step to iteratively optimize. 
What is wrong with my understanding of the paper and code?

**Comment by ronghanghu** [comment]
> In M4C paper, the output of mmt decoder is a d-dimensional vector, and we use this d-dimensional vector to calculate two scores and obtain next decoder input, which is also a d-dimensional vector.

Yes, this is exactly what happens in the code above. At step t, it predicts the t-th output word `argmax_inds[:, t]` and add it into `fwd_results["prev_inds"][:, t+1]` as input to step t+1.

In the loop above (which only happens at test time for greedy decoding), although it predicts a 12 x d vector, at each time it gradually increment the answer prediction by only one word. Since the decoder uses a causal attention mask, the i-th predicted word (i.e. `argmax_inds[:, i]`) is only determined by the inputs from index 0 to i (i.e. `fwd_results["prev_inds"][:, 0:i+1]`). Then, by `fwd_results["prev_inds"][:, 1:] = argmax_inds[:, :-1]`, the i-th predicted word will be assigned to the i+1 input index, which means that the newest predicted word will be used as the previous word in the next loop.

---
Below is an example of how this happens. Suppose the answer is `a red shirt`, which means the model wants to predict `['a', 'red', 'shirt', '<end>']` in decoding:

at time step 0, the input `prev_inds` is
`['<begin>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']`
and the output `argmax_inds` is
`['a', xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]` (here, xxx is just any arbitrary word prediction).
(`a` is predicted and added to `prev_inds`)

at time step 1, the input `prev_inds` is
`['<begin>', 'a',  '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']`
and the output `argmax_inds` is
`['a', 'red', xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]`
(`red` is predicted and added to `prev_inds`)

at time step 2, the input `prev_inds` is
`['<begin>', 'a',  'red', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']`
and the output `argmax_inds` is
`['a', 'red', 'shirt', xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]`
(`shirt` is predicted and added to `prev_inds`)

at time step 3, the input `prev_inds` is
`['<begin>', 'a',  'red', 'shirt', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']`
and the output `argmax_inds` is
`['a', 'red', 'shirt', '<end>', xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]`
(`<end>` is predicted and added to `prev_inds`)

and at step 4 to 11, the first 4 words in the output `['a', 'red', 'shirt', '<end>', ...]` won't change anymore.

**Comment by shine-lcy** [comment]
Thank you very much for your patience. Facebook is worthy of being the top company in the world.

I ran the code and output the values of `argmax_inds` and `prev_inds`.'
at time step 0, the input `prev_inds ` is
`[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`
and the output `argmax_inds ` is
`[5000, 5001,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2]`

at time step 1, the input `prev_inds` is
`[1, 5000, 5001,    2,    2,    2,    2,    2,    2,    2,    2,    2]`
and the output `argmax_inds ` is
`[5000,  339,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2]`

at time step 2, the input `prev_inds` is
`[   1, 5000,  339,    2,    2,    2,    2,    2,    2,    2,    2,    2]`


from step0 to step1, it not only updates `prev_inds[1]` to 5000 (`prev_inds[2:]` is `<pad>`), but updates `prev_inds[1:]` to `argmax_inds[1:]`. So I don't understand why you said 
> at time step 1, the input prev_inds is
`['<begin>', 'a', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']`

Corresponding to the code output, the input `prev_inds` at time step 1 should be `[1, 5000, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0]`

**Comment by ronghanghu** [comment]
(I edited my answer above.)

> from step0 to step1, it not only updates prev_inds[1] to 5000 (prev_inds[2:] is <pad>), but updates prev_inds[1:] to argmax_inds[1:]. So I don't understand why you said

Yes, it also updates `updates prev_inds[1:] to argmax_inds[1:]`. However, at step t we only care about the first t outputs (i.e. `argmax_inds[:, 0:t+1]`), and all predictions beyond index t+1 can be seen as "paddings" that will not affect the final answer prediction (since predictions beyond index t+1 will be override in subsequent prediction steps). As your example shows, the "2"s in `argmax_inds` are override by new predictions in later steps.

**Comment by shine-lcy** [comment]
The key to understand this question is `causal mask`. Thanks for ur patience! FACEBOOK FOREVER BEST!

**Comment by apsdehal** [comment]
Closing as resolved! Thanks @ronghanghu for clarifying. @shine-lcy if you have more questions, please open up a new issue.
