### ISSUE TITLE
Support For Dataset

### ISSUE THREAD

**Issue by rishika-99** [facebookresearch/mmf#554]
I wanted to know, Is there a way to use different dataset, with visual_bert.
As the mentioned datasets are :
![image](https://user-images.githubusercontent.com/70636475/92736336-d1947480-f397-11ea-977f-0d19abf383eb.png)How can I use some other dataset, other than these.  Is it possible to use a different dataset....

**Comment by vedanuj** [comment]
Hi @rishika-99 .. In order to use other datasets, you will have to add dataset and builder classes for it. You can check how the existing datasets are implemented to get an idea. Here is a tutorial notebook that shows the steps to add a new dataset : [[link](https://github.com/facebookresearch/mmf/blob/notebooks/notebooks/kdd_tutorial.ipynb)]

**Comment by rishika-99** [comment]
Hi, @vedanuj,Thanks for your reply. I read that tutorial, But I was not sure how to use it with my dataset. My dataset has 4 images and text. But the tutorial explains, how a dataset with one image and multiple statements can be registered. Can you please suggest a way, to use my dataset with mmf.
