### ISSUE TITLE
How to deal with variable length input?

### ISSUE THREAD

**Issue by hqsiswiliam** [facebookresearch/mmf#723]
## ❓ Questions and Help
Hi there,

Could somebody tell me how to deal with variable length input. Do I need to add padding to the input or the framework can do it automatically? Currently, I didn't add the padding to the input, and running it will throw an error shows:
```
AssertionError: Fields for all samples must be equally sized. item_ids is of different sizes
```

**Comment by ytsheng** [comment]
Hi @hqsiswiliam, thanks for using mmf!

I am assuming that you are referring to sentence word tokens? If so, yes, either you need to truncate it or pad it to the same size. You can take a look at the code we have within [bert_processors.py](https://github.com/facebookresearch/mmf/blob/master/mmf/datasets/processors/bert_processors.py) to see how we truncate/pad so that all the sequences are the same length.

**Comment by hqsiswiliam** [comment]
Ah, I see. I've noticed the padding part in the bert_processors, thank you.
