### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by dxu312** [facebookresearch/mmf#869]
## ❓ Questions and Help
Hi there,
I got the following error when I followed the instruction of MMF to train a model. Googled online and people have suggested reducing batch size could help. However, in my situation reducing batch size only gets the number that it "tried to allocate" smaller and still all the GPU memory is occupied. Would you please indicate what I shall do to overcome this error?
 
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 4.48 GiB already allocated; 0 bytes free; 4.80 GiB reserved in total by PyTorch)

**Comment by apsdehal** [comment]
Hi,
The issue is indeed that you don't have enough memory to run the model you are running.

Some steps you can follow:
- Before running a new job, make sure to kill older lingering job to avoid any memory reservations from those jobs.
- Make sure that `training.pin_memory` setting is `False`.
- Start with smallest batch size possible to see if you can fit it in and then try mixing it with `training.update_frequency` parameter. For example, if your original batch size is 24, you can decrease batch size to 12 and update_frequency to 2. 


Let us know if this works or not or if something is not clear.

**Comment by dxu312** [comment]
Thanks a lot for a prompt reply! I was able to get the training up to running with a batch size of 6. Would you please help clarify where the parameters you mentioned (training.pin_memory or training_update_frequency) are in the files? I can't find them in the config files.

**Comment by apsdehal** [comment]
You can override them through command line as well. Please check https://mmf.sh/docs/notes/configuration#command-line-dot-list-override
