### ISSUE TITLE
Path to builder and class

### ISSUE THREAD

**Issue by sallypannn** [facebookresearch/mmf#948]
Hi I am trying to add a new dataset. I could find where to specify the paths to dataset configs and train configs, but I could not find out how to specify the location of the new builder and class files. It shows the error message: "AssertionError: Key price_dataset doesn't have a registered dataset builder"

Can anyone help please? Thanks!

**Comment by hivestrung** [comment]
@sallypannn did you add it to the registry? 

Do have a look at this if you haven't: https://mmf.sh/docs/tutorials/dataset

Secondly, I think you might have to add a __init__.py file which imports things, and set the MMF_USER_DIR accordingly. This is depending on where you put your new dataset builder files. 

I will explain this more concretely, though I only have experience doing this for adding models rather than a dataset, it should be similar. Let's say you have your config files in `sallypannn/projects/thisproject/newdatasetconfigs` while your dataset builder class is `sallypannn/projects/thisproject/NewDBBuilder.py`

In folder `sallypannn/projects/thisproject/`, assuming you have turned this into a Python package named MyNewDataset (not sure if relative imports will work without it) add a file named __init__.py:

```
from MyNewDataset import NewDBBuilder
```

This last step is to ensure that your `@registry.register_builder("price_dataset")` actually does its job. This is how you tell MMF: "hey, here's a new builder I wrote, add it to the register!"

Then when you run mmf_run, do this:

MMF_USER_DIR='sallypannn/projects/thisproject/' mmf_run config=newdatasetconfigs/default.yaml dataset=price_dataset ...

**Comment by sallypannn** [comment]
> @sallypannn did you add it to the registry?
> 
> Do have a look at this if you haven't: https://mmf.sh/docs/tutorials/dataset
> 
> Secondly, I think you might have to add a `__init__.py` file which imports things, and set the MMF_USER_DIR accordingly. This is depending on where you put your new dataset builder files.
> 
> I will explain this more concretely, though I only have experience doing this for adding models rather than a dataset, it should be similar. Let's say you have your config files in `sallypannn/projects/thisproject/newdatasetconfigs` while your dataset builder class is `sallypannn/projects/thisproject/NewDBBuilder.py`
> 
> In folder `sallypannn/projects/thisproject/`, assuming you have turned this into a Python package named MyNewDataset (not sure if relative imports will work without it) add a file named ` __init__.py`:
> 
> ```
> from MyNewDataset import NewDBBuilder
> ```
> 
> This last step is to ensure that your `@registry.register_builder("price_dataset")` actually does its job. This is how you tell MMF: "hey, here's a new builder I wrote, add it to the register!"
> 
> Then when you run mmf_run, do this:
> 
> ```
> MMF_USER_DIR='sallypannn/projects/thisproject/' mmf_run config=newdatasetconfigs/default.yaml dataset=price_dataset ```
> 
> Tip: use `MMF_USER_DIR=$(pwd)` when in the root directory of your project if you want to avoid absolute paths, but you'll need to do `mmf_run` in the root directory if so.
> ```

Hi thanks for replying. But how can I ensure @registry.register_builder("price_dataset") actually does its job? The builder and class files work perfectly well when I put them into the corresponding location in mmf. But I would like to separate the mmf repo and my code. May I know how to handle this?

**Comment by hivestrung** [comment]
@sallypannn I just explained it, create a file `__init__.py` to import the Python class.

**Comment by sallypannn** [comment]
@hivestrung Thanks! It works for me!
